### ISSUE TITLE
Contribute back to the main fork?

### ISSUE THREAD

**Issue by robrbecker** [axel-op/github.dart#1]
@axel-op Hi! I recently took over as one of the maintainers of https://github.com/DirectMyFile/github.dart
I was looking to build some github actions for Dart when I came across your https://github.com/axel-op/dart_package_analyzer
Then I noticed you're using your own fork. I would be more than happy to get any modifications you've made merged into the published version if you'd like.
And, I just noticed https://github.com/DirectMyFile/github.dart/pull/166 .. I'll review.

**Comment by axel-op** [comment]
Also see DirectMyFile#168
